Feature: Verify Page Exists

@watch 
Scenario: validate all the current show pages

	When I URLnavigate to http://www.cbs.com/shows/american-gothic/ 
	When I URLnavigate to http://www.cbs.com/shows/beauty-and-the-beast/ 
	When I URLnavigate to http://www.cbs.com/shows/beverly-hills-90210/ 
	When I URLnavigate to http://www.cbs.com/shows/blue_bloods/ 
	When I URLnavigate to http://www.cbs.com/shows/braindead/ 
	When I URLnavigate to http://www.cbs.com/shows/bull/ 
	When I URLnavigate to http://www.cbs.com/shows/code-black/ 
	When I URLnavigate to http://www.cbs.com/shows/criminal_minds/ 
	When I URLnavigate to http://www.cbs.com/shows/criminal-minds-beyond-borders/ 
	When I URLnavigate to http://www.cbs.com/shows/csi/ 
	When I URLnavigate to http://www.cbs.com/shows/csi-cyber/ 
	When I URLnavigate to http://www.cbs.com/shows/csi-miami/ 
	When I URLnavigate to http://www.cbs.com/shows/doubt/ 
	When I URLnavigate to http://www.cbs.com/shows/elementary/ 
	When I URLnavigate to http://www.cbs.com/shows/extant/ 
	When I URLnavigate to http://www.cbs.com/shows/flashpoint/ 
	When I URLnavigate to http://www.cbs.com/shows/the-game/ 
	When I URLnavigate to http://www.cbs.com/shows/ghost-whisperer/ 
	When I URLnavigate to http://www.cbs.com/shows/the_good_wife/ 
	When I URLnavigate to http://www.cbs.com/shows/the-guardian/ 
	When I URLnavigate to http://www.cbs.com/shows/hawaii_five_0/ 
	When I URLnavigate to http://www.cbs.com/shows/hawaii-five-O-classic/ 
	When I URLnavigate to http://www.cbs.com/shows/jag/ 
	When I URLnavigate to http://www.cbs.com/shows/jericho/ 
	When I URLnavigate to http://www.cbs.com/shows/life-unexpected/ 
	When I URLnavigate to http://www.cbs.com/shows/limitless/ 
	When I URLnavigate to http://www.cbs.com/shows/macgyver/ 
	When I URLnavigate to http://www.cbs.com/shows/macgyver-classic/ 
	When I URLnavigate to http://www.cbs.com/shows/madam-secretary/ 
	When I URLnavigate to http://www.cbs.com/shows/medium/ 
	When I URLnavigate to http://www.cbs.com/shows/melrose_place/ 
	When I URLnavigate to http://www.cbs.com/shows/mission-impossible/ 
	When I URLnavigate to http://www.cbs.com/shows/nash-bridges/ 
	When I URLnavigate to http://www.cbs.com/shows/ncis/ 
	When I URLnavigate to http://www.cbs.com/shows/ncis_los_angeles/ 
	When I URLnavigate to http://www.cbs.com/shows/ncis-new-orleans/ 
	When I URLnavigate to http://www.cbs.com/shows/perry_mason/ 
	When I URLnavigate to http://www.cbs.com/shows/person_of_interest/ 
	When I URLnavigate to http://www.cbs.com/shows/pure-genius/ 
	When I URLnavigate to http://www.cbs.com/shows/rush-hour/ 
	When I URLnavigate to http://www.cbs.com/shows/scorpion/ 
	When I URLnavigate to http://www.cbs.com/shows/star_trek_deep_space_nine/ 
	When I URLnavigate to http://www.cbs.com/shows/star-trek-discovery/ 
	When I URLnavigate to http://www.cbs.com/shows/enterprise/ 
	When I URLnavigate to http://www.cbs.com/shows/star_trek_voyager/ 
	When I URLnavigate to http://www.cbs.com/shows/star_trek_the_next_generation/ 
	When I URLnavigate to http://www.cbs.com/shows/star_trek/ 
	When I URLnavigate to http://www.cbs.com/shows/touched-by-an-angel/ 
	When I URLnavigate to http://www.cbs.com/shows/training-day/ 
	When I URLnavigate to http://www.cbs.com/shows/the_twilight_zone/ 
	When I URLnavigate to http://www.cbs.com/shows/twin_peaks/ 
	When I URLnavigate to http://www.cbs.com/shows/under-the-dome/ 
	When I URLnavigate to http://www.cbs.com/shows/zoo/ 
	When I URLnavigate to http://www.cbs.com/shows/2_broke_girls/ 
	When I URLnavigate to http://www.cbs.com/shows/angel-from-hell/ 
	When I URLnavigate to http://www.cbs.com/shows/big_bang_theory/ 
	When I URLnavigate to http://www.cbs.com/shows/the_brady_bunch/ 
	When I URLnavigate to http://www.cbs.com/shows/caroline-in-the-city/ 
	When I URLnavigate to http://www.cbs.com/shows/cheers/ 
	When I URLnavigate to http://www.cbs.com/shows/everybody_hates_chris/ 
	When I URLnavigate to http://www.cbs.com/shows/family_ties/ 
	When I URLnavigate to http://www.cbs.com/shows/frasier/ 
	When I URLnavigate to http://www.cbs.com/shows/the-great-indoors/ 
	When I URLnavigate to http://www.cbs.com/shows/i_love_lucy/ 
	When I URLnavigate to http://www.cbs.com/shows/kevin-can-wait/ 
	When I URLnavigate to http://www.cbs.com/shows/life-in-pieces/ 
	When I URLnavigate to http://www.cbs.com/shows/man-with-a-plan/ 
	When I URLnavigate to http://www.cbs.com/shows/mike_and_molly/ 
	When I URLnavigate to http://www.cbs.com/the-millers/ 
	When I URLnavigate to http://www.cbs.com/shows/mom/ 
	When I URLnavigate to http://www.cbs.com/shows/the-odd-couple/ 
	When I URLnavigate to http://www.cbs.com/shows/the-odd-couple-classic/ 
	When I URLnavigate to http://www.cbs.com/shows/sabrina-the-teenage-witch/ 
	When I URLnavigate to http://www.cbs.com/shows/taxi/ 
	When I URLnavigate to http://www.cbs.com/shows/wings/ 
	When I URLnavigate to http://www.cbs.com/shows/the_bold_and_the_beautiful/ 
	When I URLnavigate to http://www.cbs.com/shows/lets_make_a_deal/ 
	When I URLnavigate to http://www.cbs.com/shows/the_price_is_right/ 
	When I URLnavigate to http://www.cbs.com/shows/the_talk/ 
	When I URLnavigate to http://www.cbs.com/shows/the_young_and_the_restless/ 
	When I URLnavigate to http://www.cbs.com/shows/cbs-dream-team/ 
	When I URLnavigate to http://www.cbs.com/shows/academy_of_country_music/ 
	When I URLnavigate to http://www.cbs.com/shows/academy_of_country_music/news/1005242/lady-antebellum-to-host-the-10th-annual-acm-honors/ 
	When I URLnavigate to http://www.cbs.com/shows/acm-sessions/ 
	When I URLnavigate to http://www.cbs.com/cbs_cares/ 
	When I URLnavigate to http://www.cbs.com/shows/cbs-fall-preview-2016/ 
	When I URLnavigate to http://www.cbs.com/shows/grammys/ 
	When I URLnavigate to http://www.cbs.com/shows/kennedy_center_honors/ 
	When I URLnavigate to http://www.cbs.com/shows/peoples_choice_awards/ 
	When I URLnavigate to http://www.cbs.com/recommended/news/1005316/stand-up-to-cancer-to-return-for-its-fifth-fundraising-event/ 
	When I URLnavigate to http://www.cbs.com/shows/thurman-vs-porter/ 
	When I URLnavigate to http://www.cbs.com/shows/tony_awards/ 
	When I URLnavigate to http://www.cbs.com/shows/victorias_secret/ 
	When I URLnavigate to http://www.cbs.com/shows/victorias-secret-swim-special/ 
	When I URLnavigate to http://www.cbs.com/shows/watch_magazine/ 
	When I URLnavigate to http://www.cbs.com/shows/amazing_race/ 
	When I URLnavigate to http://www.cbs.com/shows/big_brother/ 
	When I URLnavigate to http://www.cbs.com/shows/survivor/ 
	When I URLnavigate to http://www.cbs.com/shows/undercover_boss/ 
	When I URLnavigate to http://www.cbs.com/shows/the-late-show-with-stephen-colbert/ 
	When I URLnavigate to http://www.cbs.com/shows/late-late-show/ 
	When I URLnavigate to http://www.cbs.com/shows/48_hours/ 
	When I URLnavigate to http://www.cbs.com/shows/60_minutes/ 
	When I URLnavigate to http://www.cbs.com/shows/cbs_evening_news/ 
	When I URLnavigate to http://www.cbssports.com/ 
	When I URLnavigate to http://www.cbs.com/shows/cbs_this_morning/ 
	When I URLnavigate to http://www.cbs.com/superbowl/ 
